name: Deploy From Artifact
on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string

jobs:
  deploy-from-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Yarn
        run: yarn

      - name: Download Build Artifact (${{ inputs.package }})
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.package }}
          path: packages/${{ inputs.package }}/dist

      - name: Publish To NPM (${{ inputs.package }})
        run: yarn workspace @dannywrayuk/${{ inputs.package }} npm publish --access public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
